#! zsh

# build/update all docker containers for server

if [[ `hostname` == "server.local" ]]; then
    cd ~/Dropbox/server/images/dev
    docker build . -t ttmetro/dev
    cd ../../admin
    docker compose build
    cd ../apps
    docker compose build
else
    echo "must be on server (mac mini) to run this command!"
fi
