#! zsh

# restart admin stack

if [[ `hostname` == "server.local" ]]; then
    cd ~/Dropbox/server/stacks/apps
    docker compose down
    docker compose up -d
else
    echo "must be on server (mac mini) to run this command!"
fi
